export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

console.log('Escupe: asdf');

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="gobiernos">{children}</body>
    </html>
  );
}
