import { config } from 'dotenv';
import { games } from '../prisma/seed_data/original/games';
import { playeds } from '../prisma/seed_data/original/playeds';
import { users } from '../prisma/seed_data/original/users';
import { prisma } from '../src/database/prismaClient';

config(); // Load env file

async function run() {
  console.log('Escupe: ', playeds.length);
  console.log('Escupe: ', games.length);
}

async function run2() {
  try {
    await prisma.$transaction(
      async () => {
        await prisma.users.createMany({
          data: users,
        });
        console.log('Added seed users');
        await prisma.games.createMany({
          data: games,
        });
        console.log('Added seed games');
        await prisma.playeds.createMany({
          data: playeds,
        });
        console.log('Added seed playeds');

        // Next lines set the proper ID count for the autogenerated IDs after the seeding
        await prisma.$queryRaw`SELECT setval(pg_get_serial_sequence('games', 'id'), coalesce(max(id)+1, 1), false) FROM games;`;
        await prisma.$queryRaw`SELECT setval(pg_get_serial_sequence('playeds', 'id'), coalesce(max(id)+1, 1), false) FROM playeds;`;
        await prisma.$queryRaw`SELECT setval(pg_get_serial_sequence('users', 'id'), coalesce(max(id)+1, 1), false) FROM users;`;
      },
      {
        maxWait: 3 * 60 * 1000, // 3 minutes
        timeout: 3 * 60 * 1000, // 3 minutes
      }
    );

    console.log('Seeding process finished!');
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}

run();
